<?php

namespace App\Services;

use App\Models\AffiliateCommission;
use App\Models\Invoice;
use App\Models\Order;
use App\Models\Seller;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\DB;

class InvoiceGenerationService
{
    public function generateDraftInvoiceForSeller(int $sellerId, array $filters = [], ?Carbon $issuedAt = null): array
    {
        $issuedAt = $issuedAt ?: now();

        return DB::transaction(function () use ($sellerId, $filters, $issuedAt) {
            $ordersQuery = Order::query()
                ->where('seller_id', $sellerId)
                ->where('payment_status', 'available')
                ->whereNull('invoice_id');

            $this->applyOrderDateFilter($ordersQuery, $filters);

            $affiliateQuery = AffiliateCommission::query()
                ->where('affiliate_seller_id', $sellerId)
                ->where('status', 'available')
                ->whereNull('invoice_id');

            $this->applyAffiliateDateFilter($affiliateQuery, $filters);

            $orderIds = (clone $ordersQuery)->pluck('id');
            $affiliateIds = (clone $affiliateQuery)->pluck('id');

            if ($orderIds->isEmpty() && $affiliateIds->isEmpty()) {
                return [
                    'invoice_id' => null,
                    'orders_assigned' => 0,
                    'affiliate_commissions_assigned' => 0,
                ];
            }

            $totalOrderCommission = (float) (clone $ordersQuery)->sum('commission_amount');
            $totalAffiliateCommission = (float) (clone $affiliateQuery)->sum('amount');
            $totalCommissionValue = round($totalOrderCommission + $totalAffiliateCommission, 2);

            $invoice = Invoice::create([
                'seller_id' => $sellerId,
                'invoice_date' => $issuedAt->toDateString(),
                'invoice_time' => $issuedAt->format('H:i:s'),
                'total_commission_value' => $totalCommissionValue,
                'status' => 'draft',
            ]);

            $ordersAssigned = 0;
            if ($orderIds->isNotEmpty()) {
                $ordersAssigned = Order::query()
                    ->whereIn('id', $orderIds)
                    ->update([
                        'invoice_id' => $invoice->id,
                    ]);
            }

            $affiliateAssigned = 0;
            if ($affiliateIds->isNotEmpty()) {
                $affiliateAssigned = AffiliateCommission::query()
                    ->whereIn('id', $affiliateIds)
                    ->update([
                        'invoice_id' => $invoice->id,
                    ]);
            }

            return [
                'invoice_id' => (int) $invoice->id,
                'orders_assigned' => (int) $ordersAssigned,
                'affiliate_commissions_assigned' => (int) $affiliateAssigned,
            ];
        });
    }

    public function autoGenerateDueInvoices(?Carbon $runAt = null): array
    {
        $runAt = $runAt ?: now();
        $today = $runAt->copy()->startOfDay();

        $orderSellerIds = Order::query()
            ->where('payment_status', 'available')
            ->whereNull('invoice_id')
            ->distinct()
            ->pluck('seller_id');

        $affiliateSellerIds = AffiliateCommission::query()
            ->where('status', 'available')
            ->whereNull('invoice_id')
            ->distinct()
            ->pluck('affiliate_seller_id');

        $sellerIds = $orderSellerIds
            ->merge($affiliateSellerIds)
            ->filter()
            ->unique()
            ->values();

        if ($sellerIds->isEmpty()) {
            return [
                'invoice_count' => 0,
                'orders_assigned' => 0,
                'affiliate_commissions_assigned' => 0,
                'invoice_ids' => [],
            ];
        }

        $sellers = Seller::query()
            ->select('id', 'first_success_order_date')
            ->whereIn('id', $sellerIds)
            ->get()
            ->keyBy('id');

        $latestInvoiceDates = Invoice::query()
            ->selectRaw('seller_id, MAX(invoice_date) as latest_invoice_date')
            ->whereIn('seller_id', $sellerIds)
            ->groupBy('seller_id')
            ->pluck('latest_invoice_date', 'seller_id');

        $createdCount = 0;
        $totalOrdersAssigned = 0;
        $totalAffiliateAssigned = 0;
        $invoiceIds = [];

        foreach ($sellerIds as $sellerId) {
            $seller = $sellers->get((int) $sellerId);
            if (!$seller) {
                continue;
            }

            $dueDate = null;
            $latestInvoiceDate = $latestInvoiceDates->get((int) $sellerId);

            if (!empty($latestInvoiceDate)) {
                $invoiceCycleDays = max(1, (int) config('seller.invoice_cycle_days', 7));
                $dueDate = Carbon::parse((string) $latestInvoiceDate)
                    ->addDays($invoiceCycleDays)
                    ->startOfDay();
            } elseif (!empty($seller->first_success_order_date)) {
                $firstInvoiceDelayDays = max(0, (int) config('seller.first_invoice_delay_days', 7));
                $dueDate = Carbon::parse((string) $seller->first_success_order_date)
                    ->addDays($firstInvoiceDelayDays)
                    ->startOfDay();
            }

            if (!$dueDate || $today->lt($dueDate)) {
                continue;
            }

            $alreadyGeneratedToday = Invoice::query()
                ->where('seller_id', (int) $sellerId)
                ->whereDate('invoice_date', $today->toDateString())
                ->exists();

            if ($alreadyGeneratedToday) {
                continue;
            }

            $result = $this->generateDraftInvoiceForSeller((int) $sellerId, [], $runAt);
            if (!empty($result['invoice_id'])) {
                $createdCount++;
                $totalOrdersAssigned += (int) ($result['orders_assigned'] ?? 0);
                $totalAffiliateAssigned += (int) ($result['affiliate_commissions_assigned'] ?? 0);
                $invoiceIds[] = (int) $result['invoice_id'];
            }
        }

        return [
            'invoice_count' => $createdCount,
            'orders_assigned' => $totalOrdersAssigned,
            'affiliate_commissions_assigned' => $totalAffiliateAssigned,
            'invoice_ids' => $invoiceIds,
        ];
    }

    private function applyOrderDateFilter(Builder $query, array $filters): void
    {
        $dateType = (string) ($filters['date_type'] ?? 'order_datetime');
        $dateFrom = $filters['date_from'] ?? null;
        $dateTo = $filters['date_to'] ?? null;

        if (!empty($dateFrom)) {
            $query->whereDate($dateType, '>=', $dateFrom);
        }
        if (!empty($dateTo)) {
            $query->whereDate($dateType, '<=', $dateTo);
        }

        if (empty($dateFrom) && empty($dateTo)) {
            $orderDateFrom = $filters['order_date_from'] ?? null;
            $orderDateTo = $filters['order_date_to'] ?? null;
            $completedDateFrom = $filters['completed_date_from'] ?? null;
            $completedDateTo = $filters['completed_date_to'] ?? null;

            if (!empty($orderDateFrom)) {
                $query->whereDate('order_datetime', '>=', $orderDateFrom);
            }
            if (!empty($orderDateTo)) {
                $query->whereDate('order_datetime', '<=', $orderDateTo);
            }
            if (!empty($completedDateFrom)) {
                $query->whereDate('completed_at', '>=', $completedDateFrom);
            }
            if (!empty($completedDateTo)) {
                $query->whereDate('completed_at', '<=', $completedDateTo);
            }
        }
    }

    private function applyAffiliateDateFilter(Builder $query, array $filters): void
    {
        $dateFrom = $filters['date_from'] ?? null;
        $dateTo = $filters['date_to'] ?? null;

        if (!empty($dateFrom)) {
            $query->whereDate('available_at', '>=', $dateFrom);
        }
        if (!empty($dateTo)) {
            $query->whereDate('available_at', '<=', $dateTo);
        }

        if (empty($dateFrom) && empty($dateTo)) {
            $orderDateFrom = $filters['order_date_from'] ?? null;
            $orderDateTo = $filters['order_date_to'] ?? null;
            $completedDateFrom = $filters['completed_date_from'] ?? null;
            $completedDateTo = $filters['completed_date_to'] ?? null;

            if (!empty($orderDateFrom)) {
                $query->whereDate('available_at', '>=', $orderDateFrom);
            }
            if (!empty($orderDateTo)) {
                $query->whereDate('available_at', '<=', $orderDateTo);
            }
            if (!empty($completedDateFrom)) {
                $query->whereDate('available_at', '>=', $completedDateFrom);
            }
            if (!empty($completedDateTo)) {
                $query->whereDate('available_at', '<=', $completedDateTo);
            }
        }
    }
}
