<?php

use App\Jobs\FetchTrackingJob;
use App\Services\OrderTrackingSyncService;
use App\Services\InvoiceGenerationService;
use App\Services\SalesTargetAssessmentService;
use App\Models\Order;
use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Schedule;

Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
})->purpose('Display an inspiring quote');

Artisan::command('tracking:fetch', function (OrderTrackingSyncService $service) {
    $startedAt = now();
    $this->info('Starting tracking job dispatch at ' . $startedAt->toDateTimeString());

    $context = $service->validateTrackingContext();
    if (!($context['ready'] ?? false)) {
        $this->warn((string) ($context['message'] ?? 'Tracking context is not ready.'));
        return;
    }

    $dispatched = 0;
    Order::query()
        ->where('status', 'shipped')
        ->whereNotNull('waybill_no')
        ->orderBy('id')
        ->chunkById(200, function ($orders) use (&$dispatched) {
            foreach ($orders as $order) {
                FetchTrackingJob::dispatch((int) $order->id)->onQueue('tracking');
                $dispatched++;
            }
        });

    $this->line('Dispatched jobs: ' . $dispatched);
    $this->info('Tracking job dispatch finished at ' . now()->toDateTimeString());
})->purpose('Dispatch tracking sync jobs for shipped orders and seller progression updates.');

Schedule::command('tracking:fetch')
    ->dailyAt('21:00')
    ->timezone('Asia/Colombo')
    ->withoutOverlapping()
    ->runInBackground();

Artisan::command('finance:auto-generate-invoices', function (InvoiceGenerationService $service) {
    $startedAt = now('Asia/Colombo');
    $this->info('Starting auto invoice generation at ' . $startedAt->toDateTimeString());

    Log::info('Auto invoice generation started.', [
        'started_at' => $startedAt->toDateTimeString(),
        'timezone' => 'Asia/Colombo',
    ]);

    try {
        $result = $service->autoGenerateDueInvoices($startedAt);
    } catch (Throwable $e) {
        Log::error('Auto invoice generation failed.', [
            'started_at' => $startedAt->toDateTimeString(),
            'failed_at' => now('Asia/Colombo')->toDateTimeString(),
            'error' => $e->getMessage(),
            'exception' => $e::class,
        ]);

        throw $e;
    }

    $this->line('Generated invoices: ' . (int) ($result['invoice_count'] ?? 0));
    $this->line('Orders assigned: ' . (int) ($result['orders_assigned'] ?? 0));
    $this->line('Affiliate commissions assigned: ' . (int) ($result['affiliate_commissions_assigned'] ?? 0));

    $invoiceIds = collect($result['invoice_ids'] ?? [])->filter()->values();
    if ($invoiceIds->isNotEmpty()) {
        $this->line('Invoice IDs: ' . $invoiceIds->implode(', '));
    }

    $finishedAt = now('Asia/Colombo');

    Log::info('Auto invoice generation finished.', [
        'started_at' => $startedAt->toDateTimeString(),
        'finished_at' => $finishedAt->toDateTimeString(),
        'invoice_count' => (int) ($result['invoice_count'] ?? 0),
        'orders_assigned' => (int) ($result['orders_assigned'] ?? 0),
        'affiliate_commissions_assigned' => (int) ($result['affiliate_commissions_assigned'] ?? 0),
        'invoice_ids' => collect($result['invoice_ids'] ?? [])->filter()->values()->all(),
    ]);

    $this->info('Auto invoice generation finished at ' . $finishedAt->toDateTimeString());
})->purpose('Auto-generate seller invoices every 7 days and include affiliate commissions.');

Schedule::command('finance:auto-generate-invoices')
    ->dailyAt('04:30')
    ->timezone('Asia/Colombo')
    ->withoutOverlapping()
    ->runInBackground();

Artisan::command('sales-targets:assess', function (SalesTargetAssessmentService $service) {
    $startedAt = now('Asia/Colombo');
    $this->info('Starting sales target assessment at ' . $startedAt->toDateTimeString());

    $result = $service->assessDueTargets($startedAt);

    $this->line('Targets due: ' . (int) ($result['targets'] ?? 0));
    $this->line('Seller target results assessed: ' . (int) ($result['assessed'] ?? 0));
    $this->line('Penalties applied: ' . (int) ($result['penalties_applied'] ?? 0));
    $this->info('Sales target assessment finished at ' . now('Asia/Colombo')->toDateTimeString());
})->purpose('Assess completed sales target periods and apply seller penalties.');

Schedule::command('sales-targets:assess')
    ->dailyAt('00:15')
    ->timezone('Asia/Colombo')
    ->withoutOverlapping()
    ->runInBackground();
