<?php

use App\Jobs\FetchTrackingJob;
use App\Services\OrderTrackingSyncService;
use App\Services\InvoiceGenerationService;
use App\Models\Order;
use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Schedule;

Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
})->purpose('Display an inspiring quote');

Artisan::command('tracking:fetch', function (OrderTrackingSyncService $service) {
    $startedAt = now();
    $this->info('Starting tracking job dispatch at ' . $startedAt->toDateTimeString());

    $context = $service->validateTrackingContext();
    if (!($context['ready'] ?? false)) {
        $this->warn((string) ($context['message'] ?? 'Tracking context is not ready.'));
        return;
    }

    $dispatched = 0;
    Order::query()
        ->where('status', 'shipped')
        ->whereNotNull('waybill_no')
        ->orderBy('id')
        ->chunkById(200, function ($orders) use (&$dispatched) {
            foreach ($orders as $order) {
                FetchTrackingJob::dispatch((int) $order->id)->onQueue('tracking');
                $dispatched++;
            }
        });

    $this->line('Dispatched jobs: ' . $dispatched);
    $this->info('Tracking job dispatch finished at ' . now()->toDateTimeString());
})->purpose('Dispatch tracking sync jobs for shipped orders and seller progression updates.');

Schedule::command('tracking:fetch')
    ->dailyAt('09:00')
    ->timezone('Asia/Colombo')
    ->withoutOverlapping()
    ->runInBackground();

Artisan::command('finance:auto-generate-invoices', function (InvoiceGenerationService $service) {
    $startedAt = now();
    $this->info('Starting auto invoice generation at ' . $startedAt->toDateTimeString());

    $result = $service->autoGenerateDueInvoices($startedAt);

    $this->line('Generated invoices: ' . (int) ($result['invoice_count'] ?? 0));
    $this->line('Orders assigned: ' . (int) ($result['orders_assigned'] ?? 0));
    $this->line('Affiliate commissions assigned: ' . (int) ($result['affiliate_commissions_assigned'] ?? 0));

    $invoiceIds = collect($result['invoice_ids'] ?? [])->filter()->values();
    if ($invoiceIds->isNotEmpty()) {
        $this->line('Invoice IDs: ' . $invoiceIds->implode(', '));
    }

    $this->info('Auto invoice generation finished at ' . now()->toDateTimeString());
})->purpose('Auto-generate seller invoices every 7 days and include affiliate commissions.');

Schedule::command('finance:auto-generate-invoices')
    ->everyThirtyMinutes()
    ->timezone('Asia/Colombo')
    ->between('04:30', '06:30')
    ->withoutOverlapping()
    ->runInBackground();
